# Generated by Django 3.2.4 on 2021-06-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player', to='player.player')),
            ],
        ),
    ]
